[package]
name = "Upsilon_Multiplayer_Server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.19.0"
websocket = "0.26.5"
ws = "0.9.2"
